### ISSUE TITLE
Obuditev projekta:)

### ISSUE THREAD

**Issue by Petkomat** [TStepi/Igre#3]
Bom kr tuki objavu, da bo bolj kul.

Če nisi prezaseden, bi mogoče nadaljevala s kako kul igro:)

Torej ... Kao nej bi mela igra zapleteno taktiko pa da se ne da kr neki rešit z verjetnostmi. Vem, da sva mela vsaj ene `3`na seznamu, ampak se spomnim samo `Quoridor`ja.

**Comment by TStepi** [comment]
Hihi mal se špilam :) Čez slaba dva tedna mam ustnega pri Boru, po tem pa bi se lahk kej zmenla ja. Pa mogoč bi bil Jure tut za. Quoridor je kr zanimiva opcija ja. Sploh kr se da tut v več kot dva igralca. 
Lahk pa tuki zbirama kandidate. Js dam še vedn Blup na listo :P

**Comment by Petkomat** [comment]
Ocenjujem, ker maš ti pravice do tega repozitorija, da vprašaš Jureta in Čebišev, ga dodaš.

Tučno, Blup mi je ušev iz glave. Trenutno imamo torej
- Blup,
- Quoridor,
- tarok (simetrično + tudi licitacija je izziv),
- Juretova igra nepobarvanja `k`-cikla v polnem grafu na `n` vozliščih, kjer se manjkajoče konstante najde nekje na Wikipedii,
- zvezda (tudi simetrično in kot nalašč za tri in računsko zahtevno).

Prišel sem tudi do prebliska: ni nujno, da je igra simetrična, lahko igramo tudi po sistemu vsak z vsakim, ampak trije igralci prinesejo novo dimenzijo, morda celo dobesedno.

**Comment by Petkomat** [comment]
Izbrana je bila 3. točka:) Vidim, da smo mel kr zanimive kandidate. Ampak se mi pa zdi, da je tarok komercialno najzanimivejši.
