### ISSUE TITLE
Ali bi blo smiselno pogledat, kako se mal tipizira?

### ISSUE THREAD

**Issue by Petkomat** [TStepi/Igre#4]
Zdej sem mal pisal in sem postal rahlo paranoičen ... Bom povprašu, a je bil kdo na mypy:)

**Comment by TStepi** [comment]
Za zacetek: zakaj mesa igralec, zakaj je potrebno prevzdigovanje, zakaj se "deli" karte, ne sam premeša seznama in vzame prvih 6 za talon in preostale razdeli na #igralcev delov?
Se ti ne zdi, da totalno pretiravaš?

Deljenje kart itak spada v razred tarok, ne igralec.

**Comment by Petkomat** [comment]
Na kratko: ker sem si želel narest kopijo resničnosti.

Ker vedno meša igralec.

Neki casa sm se poigravu z mislijo, da bi naredu podrazred Matej, k bi dal talon na konc, ti bi ga dal pa na zacetk. Jure v sredin. Ampak sem se odlocu, da je to pretiravanje:) Pa da bi lah naredu tok tok namest prevzdiga.

Sej ... Zdej je konc pretiravanja po vseh kriterijih? Ostane sam se taktika. Oz. mogoče bi lah bil kamen spotike kje pri licitaciji. 

Drgač - a kodo si pognal? Trenutno sm vse importe dal s . spredi, da mi pol pycharm predlaga te stvari. Ampak potem se pa vsuje. Tko da za poganjanje je treba brez, vsaj pr men.

Pisanje prek telefona je ubijalsko. Je pa Samo Kralj Car na vlaku!

**Comment by Petkomat** [comment]
Pisanje prek telefona je ubijalsko. Je pa Samo Kralj Car na vlaku!

**Comment by Petkomat** [comment]
_Igralec,  ki  meša,  da  privzdigniti  kup  soigralcu  na  desni ter  nato  razdeli  karte  v  smeri urnega  kazalca  in  sicer  najprej  6  kart  skupaj  v  talon,  nato  pa  vsakemu  igralcu  v  dveh krogih po 8 kart. Tolčenje (namesto prevzdigovanja) ni dovoljeno._

Bom dal talon na začetku.

Ta pravila so kr eno sranje: http://www.tarok.net/pravila108.pdf (točke so že fauš)
Tu so vsaj točke ok: http://www.slovenski-tarok.si/pravila.html


Pikola bi prepovedu.

**Comment by Petkomat** [comment]
http://www.tarok.net/pravila108.pdf

**Comment by Petkomat** [comment]
Nazaj k temi tega issueja:

- sem pogledu `mypy` in pri inštalaciji rodil petorčke pri tem s carskim rezom, obup skratka
- domnevam, da za linux ni takih težav; če jih boš mel:
    - se lahko pokličemo in ti povem, kako inštalirat paket, če nau šlo
    - ker potem se postavš v mapo `tarok` in iz ukazne vrstice poženeš `mypy` in karkol si tipiziru, ti preveri

**Comment by Petkomat** [comment]
Ok, da ne bo zgube časa:

Ko enkrat maš `mypy`, je uporaba sledeča:

- v ukazni vrstici se prigoniš do `tarok` in pokličeš `mypy -p ogrodje`, ker `__init__.py`i poskrbijo, da je `ogrodje` videt kot `p`ackage. Ker mam Windows, dam na konc še dodatno opcijo `--no-fast-parser`, ker nisem uspel inštalirat paketa `typed-ast`.

Sintaksa za `mypy`:
- spremenljivke:  `x = {}  # type: Dict[Tuple[int, str], Callable[[int, int], Set[int]]]` (ključi so tupli intov pa nizov, vrednosti pa funkcije, ki sprejmejo za argumenta dva inta in vrnejo množico intov
- funkcije: `def f(x: int, y: str) -> int:` itd.
- če hočeš uporabit tip, ki ga ravno definiraš (npr. ko pišeš metodo v razredu `Igralec`), potem namest npr. `List[Igralec]` nardiš `'List[Igralec]'`
- vse te `List`, `Dict` itd. uvozš iz `typing`
